import os
 
os.system('clear')
 
os.system(' xdg-open https://github.com/fkunknownteam')
os.system('clear')

print ('Allow the Button For Access the Storage in Termux')
os.system('termux-setup-storage')
os.system('apt update -y')
os.system('pkg update -y ')
os.system('pkg upgrede -y')
os.system('pkg install git -y')
os.system('pkg install python -y')
os.system('pkg install python2 -y')
os.system('pkg install python3 -y')
os.system('pkg install curl -y')
os.system('pkg install zip -y')
os.system('pkg install php -y')
os.system('pkg install -y git zsh curl')
os.system('pkg install ruby -y')
os.system('pkg install nano -y')
os.system('pkg install httping -y')
os.system('pkg install wget -y')
os.system('pkg install bash -y')
os.system('pip install --upgrade httpie -y')
os.system('pip install --upgrade pip setuptools')
os.system('pip install bs4 -y')
os.system('pip insbasic-setup')s -y')
os.system('pip install mechanize -y')
os.system('pip install php -y')
os.system('pip2 install requests -y')
os.system('pip2 install mechanize -y')
os.system('pip2 install php -y')
os.system('pip2 install wget -y')
os.system("apt install java -y")
os.system('pip install future -y')
os.system('pkg install figlet -y') 
os.system('clear')
os.system('exit')
os.system(' cd && rm -rf basic-setup')
